services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./default.conf:/etc/nginx/conf.d/default_example.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - api
      - web

  mcp:
    build:
      context: ./mcp
      dockerfile: Dockerfile
    container_name: mcp_server
    env_file:
        - .env
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_server
    ports:
    - "8001:8001"
    env_file:
      - .env
    depends_on:
      - mcp
  web:
      build:
        context: ./my-app
        dockerfile: Dockerfile
      container_name: nextjs_web
      ports:
        - "3000:3000"
      depends_on:
        - api
