services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mcp
      - api

  mcp:
    build:
      context: ./mcp
      dockerfile: Dockerfile
    container_name: mcp_server
    ports:
    - "8080:8080"
    env_file:
        - .env
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_server
    ports:
    - "8001:8001"
    env_file:
      - .env
  web:
      build:
        context: ./my-app
        dockerfile: Dockerfile
      container_name: nextjs_web
      ports:
        - "3000:3000"
      depends_on:
        - api
